
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module sysbuildtp2(

	//////////// CLOCK //////////
	input 		          		CLOCK_50,
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,

	//////////// LED //////////
	output		     [8:0]		LEDG,
	output		    [17:0]		LEDR,

	//////////// SW //////////
	input 		    [17:0]		SW,

	//////////// SEG7 //////////
	output		     [6:0]		HEX0,
	output		     [6:0]		HEX1,
	output		     [6:0]		HEX2,
	output		     [6:0]		HEX3,
	output		     [6:0]		HEX4,
	output		     [6:0]		HEX5,
	output		     [6:0]		HEX6,
	output		     [6:0]		HEX7
);



//=======================================================
//  REG/WIRE declarations
//=======================================================

moduloTP instancia(.A(SW[17]), .B(SW[16]), .C(SW[15]), .D(SW[14]), .saida(HEX0));
maquinaAdjAdv instancia2(.clock(CLOCK_50), .ok(SW[0]), .reset(SW[1]), .fim(LEDG[8]), .tipo(LEDR[17:16]), .nota(SW[17:14]));


//=======================================================
//  Structural coding
//=======================================================



endmodule
